### ISSUE TITLE
No error

### ISSUE THREAD

**Issue by WhenUHackUNoob** [PondWader/Cubed-API#1]
No error but it looks cool! GG :D

**Comment by PondWader** [comment]
Lol, glad to know there's not an error. I'm sure that npm's download logging is broken as it definitely does not have 52 weekly downloads.

This is obviously very early WIP. Got a lot to add, like doing stuff with console, file managers, managing servers managers.

**Comment by WhenUHackUNoob** [comment]
Yeah, but still glad you done this lol. Wish you done it before when I was creating servers on cubed xD
